### ISSUE TITLE
Can only make trees up to 6 nodes

### ISSUE THREAD

**Issue by kwdoyle** [kwdoyle/phylo-compare#5]
In the first step, if an attempt to make a tree with 7 or more nodes the following error is given:

Traceback (most recent call last):
  File "framework_v2_Hirak.py", line 685, in <module>
    main()
  File "framework_v2_Hirak.py", line 672, in main
    G = forward_dmc(nodes,edges,outfile,qmod,qcon,treefile)
  File "framework_v2_Hirak.py", line 276, in forward_dmc
    G.add_edge(u,anchor_node_dic[u])
KeyError: 3

**Comment by kwdoyle** [comment]
After some tests, it appeared that this error is a random occurrence. Sometimes a larger tree is successfully created by chance.

However, the second step then requires all the object IDs to be removed from the tree file.
